var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/employees/new/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0v54o-u._.js")
R.c("server/chunks/ssr/node_modules_next_dist_060d1m.._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ixdcs~._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0~b3p9h.js")
R.c("server/chunks/ssr/[root-of-the-server]__03iv0zl._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0nafn2-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_@opentelemetry_api_index_0zv0b3p.js")
R.c("server/chunks/ssr/src_03i3n-4._.js")
R.c("server/chunks/ssr/src_app_error_tsx_0oqfei_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_employees_new_page_actions_0hlv5g0.js")
R.m(21305)
module.exports=R.m(21305).exports
