// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/17vin-billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/17vin-billing">> = Specific
  const handler = {} as typeof import("../../src/app/17vin-billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/appointments/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/appointments/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/appointments/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/appointments/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/appointments/new">> = Specific
  const handler = {} as typeof import("../../src/app/appointments/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/appointments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/appointments">> = Specific
  const handler = {} as typeof import("../../src/app/appointments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/behavior/checks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/behavior/checks">> = Specific
  const handler = {} as typeof import("../../src/app/behavior/checks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/behavior/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/behavior/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/behavior/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/companies/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/companies/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/companies/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/companies/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/companies/new">> = Specific
  const handler = {} as typeof import("../../src/app/companies/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/companies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/companies">> = Specific
  const handler = {} as typeof import("../../src/app/companies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customers/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/customers/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/customers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customers/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers/new">> = Specific
  const handler = {} as typeof import("../../src/app/customers/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers">> = Specific
  const handler = {} as typeof import("../../src/app/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employee-groups/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employee-groups/new">> = Specific
  const handler = {} as typeof import("../../src/app/employee-groups/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employee-groups/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employee-groups">> = Specific
  const handler = {} as typeof import("../../src/app/employee-groups/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employees/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employees/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/employees/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employees/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employees/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/employees/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employees/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employees/new">> = Specific
  const handler = {} as typeof import("../../src/app/employees/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/employees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employees">> = Specific
  const handler = {} as typeof import("../../src/app/employees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/finance/other-categories/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/other-categories/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/finance/other-categories/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/finance/other-categories/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/other-categories/new">> = Specific
  const handler = {} as typeof import("../../src/app/finance/other-categories/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/finance/other-categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/other-categories">> = Specific
  const handler = {} as typeof import("../../src/app/finance/other-categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/finance/other/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/other/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/finance/other/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/finance/other/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/other/new">> = Specific
  const handler = {} as typeof import("../../src/app/finance/other/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/finance/other/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/other">> = Specific
  const handler = {} as typeof import("../../src/app/finance/other/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/finance/other/payment-methods/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/other/payment-methods">> = Specific
  const handler = {} as typeof import("../../src/app/finance/other/payment-methods/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/finance/other/stats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/other/stats">> = Specific
  const handler = {} as typeof import("../../src/app/finance/other/stats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance">> = Specific
  const handler = {} as typeof import("../../src/app/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/finance/payable/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/payable">> = Specific
  const handler = {} as typeof import("../../src/app/finance/payable/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/finance/payment-methods/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/payment-methods">> = Specific
  const handler = {} as typeof import("../../src/app/finance/payment-methods/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/finance/payroll/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/payroll">> = Specific
  const handler = {} as typeof import("../../src/app/finance/payroll/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/finance/receivable/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/receivable">> = Specific
  const handler = {} as typeof import("../../src/app/finance/receivable/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/finance/transactions/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/transactions/new">> = Specific
  const handler = {} as typeof import("../../src/app/finance/transactions/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/finance/transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/transactions">> = Specific
  const handler = {} as typeof import("../../src/app/finance/transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/follow-ups/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/follow-ups/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/follow-ups/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/follow-ups/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/follow-ups">> = Specific
  const handler = {} as typeof import("../../src/app/follow-ups/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/inbound-orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inbound-orders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/inbound-orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/inbound-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inbound-orders">> = Specific
  const handler = {} as typeof import("../../src/app/inbound-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/inventory/batches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/batches">> = Specific
  const handler = {} as typeof import("../../src/app/inventory/batches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/inventory/checks/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/checks/new">> = Specific
  const handler = {} as typeof import("../../src/app/inventory/checks/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/inventory/checks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/checks">> = Specific
  const handler = {} as typeof import("../../src/app/inventory/checks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/inventory/in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/in">> = Specific
  const handler = {} as typeof import("../../src/app/inventory/in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/inventory/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/new">> = Specific
  const handler = {} as typeof import("../../src/app/inventory/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory">> = Specific
  const handler = {} as typeof import("../../src/app/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/inventory/plate-parts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/plate-parts">> = Specific
  const handler = {} as typeof import("../../src/app/inventory/plate-parts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/inventory/returns/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/returns/new">> = Specific
  const handler = {} as typeof import("../../src/app/inventory/returns/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/inventory/returns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/returns">> = Specific
  const handler = {} as typeof import("../../src/app/inventory/returns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/inventory/warehouses/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/warehouses/new">> = Specific
  const handler = {} as typeof import("../../src/app/inventory/warehouses/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/inventory/warehouses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/warehouses">> = Specific
  const handler = {} as typeof import("../../src/app/inventory/warehouses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/knowledge/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/knowledge/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/knowledge/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/knowledge/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/knowledge/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/knowledge/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/knowledge/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/knowledge/categories">> = Specific
  const handler = {} as typeof import("../../src/app/knowledge/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/knowledge/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/knowledge/new">> = Specific
  const handler = {} as typeof import("../../src/app/knowledge/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/knowledge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/knowledge">> = Specific
  const handler = {} as typeof import("../../src/app/knowledge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/logistics/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistics/new">> = Specific
  const handler = {} as typeof import("../../src/app/logistics/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/logistics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistics">> = Specific
  const handler = {} as typeof import("../../src/app/logistics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/assignment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/assignment">> = Specific
  const handler = {} as typeof import("../../src/app/m/assignment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/inspection/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/inspection">> = Specific
  const handler = {} as typeof import("../../src/app/m/inspection/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/other/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/other/new">> = Specific
  const handler = {} as typeof import("../../src/app/m/other/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/other/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/other">> = Specific
  const handler = {} as typeof import("../../src/app/m/other/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m">> = Specific
  const handler = {} as typeof import("../../src/app/m/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/picking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/picking">> = Specific
  const handler = {} as typeof import("../../src/app/m/picking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/quote/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/quote">> = Specific
  const handler = {} as typeof import("../../src/app/m/quote/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/receiving/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/receiving">> = Specific
  const handler = {} as typeof import("../../src/app/m/receiving/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/reception/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/reception/new">> = Specific
  const handler = {} as typeof import("../../src/app/m/reception/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/reception/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/reception">> = Specific
  const handler = {} as typeof import("../../src/app/m/reception/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mechanic-levels/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mechanic-levels/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/mechanic-levels/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mechanic-levels/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mechanic-levels/new">> = Specific
  const handler = {} as typeof import("../../src/app/mechanic-levels/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mechanic-levels/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mechanic-levels">> = Specific
  const handler = {} as typeof import("../../src/app/mechanic-levels/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/members/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/members/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/members/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/members/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/members/new">> = Specific
  const handler = {} as typeof import("../../src/app/members/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/members/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/members">> = Specific
  const handler = {} as typeof import("../../src/app/members/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/operation-logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operation-logs">> = Specific
  const handler = {} as typeof import("../../src/app/operation-logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/outsource-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/outsource-orders">> = Specific
  const handler = {} as typeof import("../../src/app/outsource-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/part-brands/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/part-brands/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/part-brands/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/part-brands/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/part-brands/new">> = Specific
  const handler = {} as typeof import("../../src/app/part-brands/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/part-brands/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/part-brands">> = Specific
  const handler = {} as typeof import("../../src/app/part-brands/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/part-categories/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/part-categories/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/part-categories/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/part-categories/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/part-categories/new">> = Specific
  const handler = {} as typeof import("../../src/app/part-categories/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/part-categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/part-categories">> = Specific
  const handler = {} as typeof import("../../src/app/part-categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/part-names/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/part-names/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/part-names/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/part-names/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/part-names/new">> = Specific
  const handler = {} as typeof import("../../src/app/part-names/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/part-names/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/part-names">> = Specific
  const handler = {} as typeof import("../../src/app/part-names/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/part-specifications/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/part-specifications/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/part-specifications/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/part-specifications/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/part-specifications/new">> = Specific
  const handler = {} as typeof import("../../src/app/part-specifications/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/part-specifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/part-specifications">> = Specific
  const handler = {} as typeof import("../../src/app/part-specifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/parts/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/parts/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/parts/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/parts/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/parts/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/parts/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/parts/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/parts/new">> = Specific
  const handler = {} as typeof import("../../src/app/parts/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/procurement/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/procurement/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/procurement/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/procurement/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/procurement/new">> = Specific
  const handler = {} as typeof import("../../src/app/procurement/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/procurement/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/procurement/orders">> = Specific
  const handler = {} as typeof import("../../src/app/procurement/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/procurement/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/procurement">> = Specific
  const handler = {} as typeof import("../../src/app/procurement/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reminders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reminders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/reminders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reminders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reminders">> = Specific
  const handler = {} as typeof import("../../src/app/reminders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reports/auto-linked-parts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/auto-linked-parts">> = Specific
  const handler = {} as typeof import("../../src/app/reports/auto-linked-parts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reports/construction-stats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/construction-stats">> = Specific
  const handler = {} as typeof import("../../src/app/reports/construction-stats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reports/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/inventory">> = Specific
  const handler = {} as typeof import("../../src/app/reports/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../src/app/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reports/performance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/performance">> = Specific
  const handler = {} as typeof import("../../src/app/reports/performance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reports/procurement/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/procurement">> = Specific
  const handler = {} as typeof import("../../src/app/reports/procurement/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reports/profit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/profit">> = Specific
  const handler = {} as typeof import("../../src/app/reports/profit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reports/revenue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/revenue">> = Specific
  const handler = {} as typeof import("../../src/app/reports/revenue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reports/work-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/work-orders">> = Specific
  const handler = {} as typeof import("../../src/app/reports/work-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/return-orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/return-orders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/return-orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/return-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/return-orders">> = Specific
  const handler = {} as typeof import("../../src/app/return-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/service-categories/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/service-categories/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/service-categories/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/service-categories/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/service-categories/new">> = Specific
  const handler = {} as typeof import("../../src/app/service-categories/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/service-categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/service-categories">> = Specific
  const handler = {} as typeof import("../../src/app/service-categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/service-items/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/service-items/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/service-items/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/service-items/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/service-items/new">> = Specific
  const handler = {} as typeof import("../../src/app/service-items/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/service-items/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/service-items">> = Specific
  const handler = {} as typeof import("../../src/app/service-items/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/service-names/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/service-names/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/service-names/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/service-names/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/service-names/new">> = Specific
  const handler = {} as typeof import("../../src/app/service-names/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/service-names/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/service-names">> = Specific
  const handler = {} as typeof import("../../src/app/service-names/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/supplier-returns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/supplier-returns">> = Specific
  const handler = {} as typeof import("../../src/app/supplier-returns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/supplier-transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/supplier-transactions">> = Specific
  const handler = {} as typeof import("../../src/app/supplier-transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/suppliers/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/suppliers/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/suppliers/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/suppliers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/suppliers/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/suppliers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/suppliers/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/suppliers/new">> = Specific
  const handler = {} as typeof import("../../src/app/suppliers/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/suppliers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/suppliers">> = Specific
  const handler = {} as typeof import("../../src/app/suppliers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tags/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tags">> = Specific
  const handler = {} as typeof import("../../src/app/tags/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tools/vin-batch-query/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tools/vin-batch-query">> = Specific
  const handler = {} as typeof import("../../src/app/tools/vin-batch-query/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/training/[id]/assign/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training/[id]/assign">> = Specific
  const handler = {} as typeof import("../../src/app/training/[id]/assign/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/training/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/training/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/training/[id]/exam/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training/[id]/exam">> = Specific
  const handler = {} as typeof import("../../src/app/training/[id]/exam/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/training/[id]/grade-entry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training/[id]/grade-entry">> = Specific
  const handler = {} as typeof import("../../src/app/training/[id]/grade-entry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/training/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/training/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/training/behavior-checks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training/behavior-checks">> = Specific
  const handler = {} as typeof import("../../src/app/training/behavior-checks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/training/behavior-items/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training/behavior-items">> = Specific
  const handler = {} as typeof import("../../src/app/training/behavior-items/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/training/behavior-score/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training/behavior-score">> = Specific
  const handler = {} as typeof import("../../src/app/training/behavior-score/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/training/behavior-tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training/behavior-tasks">> = Specific
  const handler = {} as typeof import("../../src/app/training/behavior-tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/training/exam-grade/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training/exam-grade">> = Specific
  const handler = {} as typeof import("../../src/app/training/exam-grade/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/training/exam-manage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training/exam-manage">> = Specific
  const handler = {} as typeof import("../../src/app/training/exam-manage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/training/loss-records/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training/loss-records">> = Specific
  const handler = {} as typeof import("../../src/app/training/loss-records/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/training/my-progress/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training/my-progress">> = Specific
  const handler = {} as typeof import("../../src/app/training/my-progress/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/training/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training/new">> = Specific
  const handler = {} as typeof import("../../src/app/training/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/training/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training">> = Specific
  const handler = {} as typeof import("../../src/app/training/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/training/promotion-overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training/promotion-overview">> = Specific
  const handler = {} as typeof import("../../src/app/training/promotion-overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/training/promotion-records/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training/promotion-records">> = Specific
  const handler = {} as typeof import("../../src/app/training/promotion-records/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/training/promotion-rules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training/promotion-rules">> = Specific
  const handler = {} as typeof import("../../src/app/training/promotion-rules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/training/promotion-status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training/promotion-status">> = Specific
  const handler = {} as typeof import("../../src/app/training/promotion-status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/training/rework-records/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/training/rework-records">> = Specific
  const handler = {} as typeof import("../../src/app/training/rework-records/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/vehicle-models/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vehicle-models">> = Specific
  const handler = {} as typeof import("../../src/app/vehicle-models/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/vehicles/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vehicles/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/vehicles/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/vehicles/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vehicles/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/vehicles/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/vehicles/[id]/templates/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vehicles/[id]/templates/new">> = Specific
  const handler = {} as typeof import("../../src/app/vehicles/[id]/templates/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/vehicles/[id]/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vehicles/[id]/templates">> = Specific
  const handler = {} as typeof import("../../src/app/vehicles/[id]/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/vehicles/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vehicles/new">> = Specific
  const handler = {} as typeof import("../../src/app/vehicles/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/vehicles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vehicles">> = Specific
  const handler = {} as typeof import("../../src/app/vehicles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/work-orders/[id]/inspection/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/work-orders/[id]/inspection/new">> = Specific
  const handler = {} as typeof import("../../src/app/work-orders/[id]/inspection/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/work-orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/work-orders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/work-orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/work-orders/[id]/payment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/work-orders/[id]/payment">> = Specific
  const handler = {} as typeof import("../../src/app/work-orders/[id]/payment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/work-orders/[id]/print/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/work-orders/[id]/print">> = Specific
  const handler = {} as typeof import("../../src/app/work-orders/[id]/print/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/work-orders/[id]/reception/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/work-orders/[id]/reception/new">> = Specific
  const handler = {} as typeof import("../../src/app/work-orders/[id]/reception/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/work-orders/[id]/reimbursement/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/work-orders/[id]/reimbursement">> = Specific
  const handler = {} as typeof import("../../src/app/work-orders/[id]/reimbursement/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/work-orders/[id]/requirements/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/work-orders/[id]/requirements/new">> = Specific
  const handler = {} as typeof import("../../src/app/work-orders/[id]/requirements/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/work-orders/board/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/work-orders/board">> = Specific
  const handler = {} as typeof import("../../src/app/work-orders/board/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/work-orders/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/work-orders/new">> = Specific
  const handler = {} as typeof import("../../src/app/work-orders/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/work-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/work-orders">> = Specific
  const handler = {} as typeof import("../../src/app/work-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/work-orders/part-board/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/work-orders/part-board">> = Specific
  const handler = {} as typeof import("../../src/app/work-orders/part-board/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/employees/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/employees/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/employees/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/employees/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/employees">> = Specific
  const handler = {} as typeof import("../../src/app/api/employees/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/media/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/[...path]">> = Specific
  const handler = {} as typeof import("../../src/app/api/media/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/proxy-image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proxy-image">> = Specific
  const handler = {} as typeof import("../../src/app/api/proxy-image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/m">> = Specific
  const handler = {} as typeof import("../../src/app/m/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
