var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/training/promotion-status/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__06sbz1s._.js")
R.c("server/chunks/ssr/node_modules_next_dist_060d1m.._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ixdcs~._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0c_gcs..js")
R.c("server/chunks/ssr/[root-of-the-server]__03iv0zl._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0nafn2-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_@opentelemetry_api_index_0zv0b3p.js")
R.c("server/chunks/ssr/src_03i3n-4._.js")
R.c("server/chunks/ssr/src_app_error_tsx_0oqfei_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_training_promotion-status_page_actions_08aax34.js")
R.m(91852)
module.exports=R.m(91852).exports
