var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/vehicles/new/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0vdtht0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_060d1m.._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ixdcs~._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_132jnlj.js")
R.c("server/chunks/ssr/[root-of-the-server]__03iv0zl._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0nafn2-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_@opentelemetry_api_index_0zv0b3p.js")
R.c("server/chunks/ssr/src_03i3n-4._.js")
R.c("server/chunks/ssr/src_app_error_tsx_0oqfei_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/[root-of-the-server]__0jofm7_._.js")
R.c("server/chunks/ssr/node_modules_@supabase_supabase-js_dist_index_mjs_04qodwz._.js")
R.m(63840)
module.exports=R.m(63840).exports
